version: '3.8'

services:
  postgres:
    image: postgres:14.3
    container_name: taxi-live
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taxi-live
    ports:
      - "5433:5433"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql